name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install dependencies
      run: composer install
    - name: Create SQLite database
      run: touch database/testing.sqlite
    - name: Run migrations
      run: php artisan migrate --env=testing
    - name: Run tests
      run: php artisan test --env=testing
    - name: Force failure
      run: exit 1
    - name: Notify on failure
      if: failure()
      run: ./send_email.sh failed
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        GITHUB_ACTOR: ${{ github.actor }}
